// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINJdo1gBn3p02hAXXcU0F0_CrIcpDXCs',
    appId: '1:804062564130:web:4aff213d3274c4e68b1f7b',
    messagingSenderId: '804062564130',
    projectId: 'fir-koko-5095a',
    authDomain: 'fir-koko-5095a.firebaseapp.com',
    storageBucket: 'fir-koko-5095a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCddvh1P5n8n4HEzR_i9dFeReMwl1qgkG0',
    appId: '1:804062564130:android:079eff555098ad3c8b1f7b',
    messagingSenderId: '804062564130',
    projectId: 'fir-koko-5095a',
    storageBucket: 'fir-koko-5095a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVukvrVsQcnyTdDVrTiieLHugInGYXqKk',
    appId: '1:804062564130:ios:cfcc92a5ae8c63608b1f7b',
    messagingSenderId: '804062564130',
    projectId: 'fir-koko-5095a',
    storageBucket: 'fir-koko-5095a.appspot.com',
    iosClientId: '804062564130-kkr10tm9rkstgv6ukfbusi6e76ndeu7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAuthKoko',
  );
}
